### ISSUE TITLE
Server side

### ISSUE THREAD

**Issue by CodingLady22** [CodingLady22/skizzy-fast-food#28]
## Description
Add a server-side to the website. Set up the basic folder structure to run the server side code

### Tasks

- [ ] Create an entry file
- [ ] Install the necessary packages
- [ ] Set up the entry file so it can be accessed on the localhost
- [ ] connect server side to client side
